### ISSUE TITLE
ValueError: need more than 0 values to unpack

### ISSUE THREAD

**Issue by urumo** [jisungk/deepjazz#10]
Traceback (most recent call last):
  File "generator.py", line 193, in <module>
    main(sys.argv)
  File "generator.py", line 188, in main
    generate(data_fn, out_fn, N_epochs)
  File "generator.py", line 107, in generate
    chords, abstract_grammars = get_musical_data(data_fn)
  File "/media/aram/Mordigan/How-to-Generate-Music-Demo-master/preprocess.py", line 130, in get_musical_data
    measures, chords = __parse_midi(data_fn)
  File "/media/aram/Mordigan/How-to-Generate-Music-Demo-master/preprocess.py", line 25, in __parse_midi
    melody1, melody2 = melody_stream.getElementsByClass(stream.Voice)
ValueError: need more than 0 values to unpack

and what do I do now?

**Comment by Echo-Ji** [comment]
ADVISE:
You can just use "try-except" to catch the exception and debug it.
code like:
```
    try:
        melody1, melody2 = melody_stream.getElementsByClass(stream.Voice)
    except:
        print line
```
