### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'mode'

### ISSUE THREAD

**Issue by orchestor** [jisungk/deepjazz#8]
Try to run the script but failed. Any pointer?
```
Using Theano backend.
Traceback (most recent call last):
  File "generator.py", line 193, in <module>
    main(sys.argv)
  File "generator.py", line 188, in main
    generate(data_fn, out_fn, N_epochs)
  File "generator.py", line 107, in generate
    chords, abstract_grammars = get_musical_data(data_fn)
  File "/Users/grant/project/deepjazz/preprocess.py", line 130, in get_musical_data
    measures, chords = __parse_midi(data_fn)
  File "/Users/grant/project/deepjazz/preprocess.py", line 37, in __parse_midi
    melody_voice.insert(0, key.KeySignature(sharps=1, mode='major'))
TypeError: __init__() got an unexpected keyword argument 'mode'

**Comment by jisungk** [comment]
It appears that there's been an [API change for the music21 library](http://web.mit.edu/music21/doc/moduleReference/moduleKey.html).

**Comment by gofornaman** [comment]
How to fix this?

**Comment by dkun7944** [comment]
@jisungk Which version of music21 works with deepjazz?

**Comment by GyeowoonJeong** [comment]
@jisungk Can you explain me about how can I fix this error?
